CREATE TABLE "alumnos" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar NOT NULL,
  "descripcion" text,
  "clases_id" integer NOT NULL,
  "dormitorios_id" integer NOT NULL,
  "nacimiento_id" integer NOT NULL,
  "trabajo_id" integer NOT NULL
);

CREATE TABLE "clases" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "titulo" varchar,
  "descripcion" text,
  "salones_id" integer NOT NULL,
  "talleres_id" integer NOT NULL
);

CREATE TABLE "poblacion" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar NOT NULL,
  "descripcion" text
);

CREATE TABLE "salones" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "titulo" varchar NOT NULL,
  "descripcion" text,
  "talleres_id" integer NOT NULL
);

CREATE TABLE "talleres" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "titulo" varchar NOT NULL,
  "descripcion" text
);

CREATE TABLE "dormitorios" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "titulo" varchar NOT NULL,
  "descripcion" text,
  "cupo" integer NOT NULL
);

CREATE TABLE "metadata_libro" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "titulo" varchar NOT NULL,
  "descripcion" text
);

CREATE TABLE "clases_salones" (
  "clases_id" int,
  "salones_id" int
);

CREATE TABLE "clases_talleres" (
  "clases_id" int,
  "talleres_id" int
);

CREATE TABLE "alumnos_clases" (
  "clases_id" int,
  "alumnos_id" int
);

COMMENT ON COLUMN "alumnos"."descripcion" IS 'Descripción del alumno';

COMMENT ON COLUMN "clases"."descripcion" IS 'Descripción de la clase o materia';

COMMENT ON COLUMN "poblacion"."descripcion" IS 'Descripción del lugar de nacimiento o de trabajo';

COMMENT ON COLUMN "salones"."descripcion" IS 'Descripción del salon';

COMMENT ON COLUMN "talleres"."descripcion" IS 'Descripción del taller';

COMMENT ON COLUMN "dormitorios"."descripcion" IS 'Descripción del dormitorio';

COMMENT ON COLUMN "metadata_libro"."descripcion" IS 'Descripción de la metadata del libro';

ALTER TABLE "clases_salones" ADD FOREIGN KEY ("clases_id") REFERENCES "clases" ("id");

ALTER TABLE "clases_salones" ADD FOREIGN KEY ("salones_id") REFERENCES "salones" ("id");

ALTER TABLE "clases_talleres" ADD FOREIGN KEY ("clases_id") REFERENCES "clases" ("id");

ALTER TABLE "clases_talleres" ADD FOREIGN KEY ("talleres_id") REFERENCES "talleres" ("id");

ALTER TABLE "alumnos_clases" ADD FOREIGN KEY ("clases_id") REFERENCES "clases" ("id");

ALTER TABLE "alumnos_clases" ADD FOREIGN KEY ("alumnos_id") REFERENCES "alumnos" ("id");

ALTER TABLE "alumnos" ADD FOREIGN KEY ("nacimiento_id") REFERENCES "poblacion" ("id");

ALTER TABLE "alumnos" ADD FOREIGN KEY ("trabajo_id") REFERENCES "poblacion" ("id");

ALTER TABLE "alumnos" ADD FOREIGN KEY ("dormitorios_id") REFERENCES "dormitorios" ("id");

ALTER TABLE "alumnos" ADD FOREIGN KEY ("clases_id") REFERENCES "clases" ("id");
